/* -------------------------------------------------------------------------
   Payment is via a static Venmo QR code printed and posted at the register —
   not generated by this app. See POPUP.md. What this module gives the
   cashier is the note to suggest the customer add to their payment, so
   incoming Venmo activity can be matched back to the right order.
   ------------------------------------------------------------------------- */

export const venmoNote = order =>
  `-hyphenate #${order.number}${order.name ? ` · ${order.name}` : ''}`;
